services:
  token-server:
    # image: jqtype/token-server:latest
    image: jqtype/token-server:slim
    container_name: token-server
    build:
      context: .
      # dockerfile: ./Dockerfile
      dockerfile: ./Dockerfile-slim
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 8000:8000/udp
      - 8000:8000/tcp
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8000/health || exit 1"]
    volumes:
      - ./server/.env:/opt/token-server/etc/.env
    #   - ${SIGNING_KEY_PATH}:/opt/token-server/etc/private_key.pem
    #   - ${DATA_DIR_PATH}:/opt/token-server/var/
    #   - ${LOG_DIR}:/var/log/token-server/
    # networks:
    # net-front:

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   command: dnscrypt-server --interval 30
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
# networks:
# net-front:
# external: true
