name: Build and Publish Docker

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: id-token-server
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: "default"
            dockerfile: ./Dockerfile
            platforms: linux/amd64
            # Aliases must be used only for release builds
            aliases: |
              jqtype/id-token-server:latest
          - target: "slim"
            dockerfile: ./Dockerfile-slim
            platforms: linux/amd64
            tags-suffix: "-slim"
            # Aliases must be used only for release builds
            aliases: |
              jqtype/id-token-server:slim

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: GitHub Environment
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release build and push x86_64
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest${{ matrix.tags-suffix }}
            ${{ matrix.aliases }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}

      - name: Nightly build and push x86_64
        if: ${{ github.ref_name == 'develop' }}
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:nightly${{ matrix.tags-suffix }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
